image:
  name: "hashicorp/terraform"
  entrypoint: [""]

stages:
  - "validate"
#  - "markdownlint"
  - "deploy"

terraformvalidate:
  stage: validate
  script:
  - "terraform init terraform"
  - "terraform validate terraform"

#markdownlint:
#  stage: validate
#  image: pipelinecomponents/markdownlint:latest
#  allow_failure: true
#  script:
#    - mdl --style all --warnings .

deploy:
  stage: "deploy"
  only:
    - "master"
  script:
  - "apk add ansible"
  - "chmod 0600 terraform/aws-kurs"
  - "terraform init terraform"
  #- "terraform apply -auto-approve terraform"
  - "terraform destroy -auto-approve terraform"
