image:
  name: "hashicorp/terraform"
  entrypoint: [""]

before_script:
  - "terraform init terraform"

stages:
  - "validate"
  - "deploy"

validate:
  stage: "validate"
  script:
  - "terraform init terraform"
  - "terraform validate terraform"

deploy:
  stage: "deploy"
  only:
    - "master"
  script:
  - "apk add ansible"
  - "terraform $TF_ACTION -auto-approve terraform"
