image:
  name: "hashicorp/terraform"
  entrypoint: [""]

before_script:
  - "terraform init /builds/bosse/ansible-lab/terraform"

test:
  script:
  - "pwd"
  - "terraform validate /builds/bosse/ansible-lab/terraform"
