image:
  name: "hashicorp/terraform"
  entrypoint: [""]

test:
  script:
  - "terraform init terraform"
  - "terraform validate terraform"

deploy:
  script:
  - "apk add ansible"
  - "terraform apply -auto-approve terraform"
