image:
  name: "hashicorp/terraform"
  entrypoint: [""]

before_script:
  - "terraform init terraform"

test:
  script:
  - "terraform validate terraform"

test:
  script:
  - "terraform apply -auto-approve terraform"
