image:
  name: "hashicorp/terraform"
  entrypoint: [""]

before_script:
  - "yum install -y epel-release"
  - "yum install -y terraform"
  - "terraform init terraform"

test:
  script:
  - "terraform validate terraform"

test:
  script:
  - "yum install -y ansible"
  - "terraform apply -auto-approve terraform"
