image:
  name: "hashicorp/terraform"
  entrypoint: [""]

before_script:
  - "terraform init terraform"

test:
  script:
  - "terraform init terraform"
  - "terraform validate terraform"

deploy:
  script:
  - "apk add ansible"
  - "terraform destroy -auto-approve terraform"
