---
hosts: webservers
become: true
tasks:

- name: Install Apache
  package:
    name: httpd
    state: present

- name: Install PHP
  package:
    name: php
    state: present

- name: Enable services
  service:
    name: httpd
    state: started
    enable: true

- name: Enable services PHP
  service:
    name: php
    state: started
    enable: true
